### ISSUE TITLE
Error when running demo

### ISSUE THREAD

**Issue by dzhao123** [YingyuLiang/SIF_mini_demo#5]
So I am trying to run the demo but there is an error report, can you give me some hints about it? Thanks.

```
Traceback (most recent call last):
  File "sif_embedding.py", line 13, in <module>
    (words, We) = data_io.getWordmap(wordfile)
  File "../src/data_io.py", line 18, in getWordmap
    v.append(float(i[j]))
ValueError: could not convert string to float: '.'

```

**Comment by Cumberbatch08** [comment]
If you print the line , you will find that I word is not a simple word, it may be ‘...’ '@ google.com', you can add len(line) == 301 to assert.
